GRAMMAR_DATA = {
    "past-simple": {
        "title": "Past Simple",
        "category": "past",
        "bg_image": "https://images.unsplash.com/photo-1760410802787-093c3d3f6cee?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "formula": "Did / didn't + V2/-ed",
        "card_formula": "V2 — друга форма з таблиці неправильних дієслів або закінчення -ed",
        "affirmative": "I/You/He/She/It/We/They +V2 /-ed",
        "negative": "Did + not + V1 (didn't + V1)",
        "question": "Did + I / you / he... + V1?",
        "examples": [
            "I wrote code yesterday (+) ",
            "She visited her grandparents (+) ",
            "They didn't play football (-) ",
            "He didn't watch a movie (-) ",
            "Did you code yesterday (?) ",
            "Did she visit them (?) "
        ],
        "description": "Використовується для дій, які завершилися в минулому в конкретний час.",
        "usage": [
            "Дія, яка сталася в минулому і вже закінчилася",
            "Послідовність дій у минулому"
        ],
        "keywords": [
            "yesterday (вчора)",
            "last week / month (минулого тижня / місяця)",
            "ago (тому)"
        ],
        "color": "purple",
        "questions": [
            {"question": "I ___ (write) a letter to my friend yesterday.", "options": ["wrote", "write", "had written"], "answer": "wrote"},
            {"question": "She ___ (go) to the supermarket an hour ago.", "options": ["went", "goed", "goes"], "answer": "went"},
            {"question": "They ___ (play) football last Sunday.", "options": ["played", "play", "were playing"], "answer": "played"},
            {"question": "He ___ (not / buy) a new car last month.", "options": ["didn't buy", "doesn't buy", "wasn't buying"], "answer": "didn't buy"},
            {"question": "___ you see that movie on TV last night?", "options": ["Did", "Do", "Were"], "answer": "Did"},
            {"question": "We ___ (be) very tired after the trip.", "options": ["were", "was", "are"], "answer": "were"},
            {"question": "She ___ (cook) a delicious dinner yesterday.", "options": ["cooked", "cooks", "has cooked"], "answer": "cooked"},
            {"question": "What time ___ you wake up this morning?", "options": ["did", "do", "were"], "answer": "did"},
            {"question": "The train ___ (arrive) ten minutes late.", "options": ["arrived", "arrive", "has arrived"], "answer": "arrived"},
            {"question": "I ___ (not / know) the answer to the test question.", "options": ["didn't know", "don't know", "wasn't knowing"], "answer": "didn't know"},
            {"question": "He ___ (read) an interesting book last week.", "options": ["read", "reads", "is reading"], "answer": "read"},
            {"question": "Where ___ they spend their summer vacation?", "options": ["did", "do", "were"], "answer": "did"},
            {"question": "The dog ___ (bark) all night long.", "options": ["barked", "barks", "bark"], "answer": "barked"},
            {"question": "She ___ (meet) her old school friend downtown.", "options": ["met", "meet", "has met"], "answer": "met"},
            {"question": "It ___ (start) to rain while we were walking.", "options": ["started", "starts", "was starting"], "answer": "started"},
            {"question": "We ___ (clean) the whole house on Saturday.", "options": ["cleaned", "clean", "have cleaned"], "answer": "cleaned"},
            {"question": "Why ___ you cry during the movie?", "options": ["did", "do", "were"], "answer": "did"},
            {"question": "He ___ (lose) his keys at the office.", "options": ["lost", "lose", "losed"], "answer": "lost"},
            {"question": "They ___ (sell) their old house last year.", "options": ["sold", "sells", "have sold"], "answer": "sold"},
            {"question": "I ___ (forget) to call you yesterday.", "options": ["forgot", "forget", "have forgotten"], "answer": "forgot"},
            {"question": "She ___ (paint) this picture in 2015.", "options": ["painted", "paint", "has painted"], "answer": "painted"},
            {"question": "___ you enjoy the party last weekend?", "options": ["Did", "Do", "Were"], "answer": "Did"},
            {"question": "We ___ (not / spend) much money on the trip.", "options": ["didn't spend", "don't spend", "weren't spending"], "answer": "didn't spend"},
            {"question": "He ___ (catch) a big fish in the river.", "options": ["caught", "catched", "catch"], "answer": "caught"},
            {"question": "The wind ___ (blow) our garden fence down.", "options": ["blew", "blowed", "blown"], "answer": "blew"},
            {"question": "Who ___ you talk to after the meeting?", "options": ["did", "do", "were"], "answer": "did"},
            {"question": "She ___ (wear) her best dress to the gala.", "options": ["wore", "weared", "worn"], "answer": "wore"},
            {"question": "They ___ (build) this bridge centuries ago.", "options": ["built", "builded", "have built"], "answer": "built"},
            {"question": "I ___ (find) a wallet on the street.", "options": ["found", "find", "founded"], "answer": "found"},
            {"question": "The teacher ___ (explain) the grammar rule clearly.", "options": ["explained", "explain", "was explaining"], "answer": "explained"}
        ]
    },
    "present-simple": {
        "title": "Present Simple",
        "category": "present",
        "bg_image": "https://images.unsplash.com/photo-1551992165-eb78b2b046b3?q=80&w=1976&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "formula": "Do / does + V1",
        "examples": ["I write code"],
        "color": "blue",
        "questions": [
            {"question": "She ___ (work) as a designer in a local company.", "options": ["works", "work", "is working"], "answer": "works"},
            {"question": "They ___ (not / like) to wake up early on Sundays.", "options": ["don't like", "doesn't like", "aren't liking"], "answer": "don't like"},
            {"question": "___ your friend live in this neighborhood?", "options": ["Does", "Do", "Is"], "answer": "Does"},
            {"question": "Water ___ (boil) at 100 degrees Celsius.", "options": ["boils", "boil", "is boiling"], "answer": "boils"},
            {"question": "I usually ___ (drink) coffee in the morning.", "options": ["drink", "drinks", "am drinking"], "answer": "drink"},
            {"question": "He ___ (not / play) tennis on weekdays.", "options": ["doesn't play", "don't play", "isn't playing"], "answer": "doesn't play"},
            {"question": "___ you speak English fluently?", "options": ["Do", "Does", "Are"], "answer": "Do"},
            {"question": "The sun ___ (rise) in the east.", "options": ["rises", "rise", "is rising"], "answer": "rises"},
            {"question": "My parents ___ (live) in a big house.", "options": ["live", "lives", "are living"], "answer": "live"},
            {"question": "Cats ___ (hate) getting wet in the rain.", "options": ["hate", "hates", "are hating"], "answer": "hate"},
            {"question": "She ___ (study) Spanish at university.", "options": ["studies", "study", "is studying"], "answer": "studies"},
            {"question": "We ___ (not / watch) TV very often.", "options": ["don't watch", "doesn't watch", "aren't watching"], "answer": "don't watch"},
            {"question": "___ your brother have a driving license?", "options": ["Does", "Do", "Has"], "answer": "Does"},
            {"question": "Good students ___ (do) their homework regularly.", "options": ["do", "does", "are doing"], "answer": "do"},
            {"question": "The bank ___ (open) at 9:00 AM every day.", "options": ["opens", "open", "is opening"], "answer": "opens"},
            {"question": "He ___ (always / help) his friends in trouble.", "options": ["always helps", "always help", "is always helping"], "answer": "always helps"},
            {"question": "They ___ (not / eat) fast food.", "options": ["don't eat", "doesn't eat", "aren't eating"], "answer": "don't eat"},
            {"question": "___ birds migrate south for the winter?", "options": ["Do", "Does", "Are"], "answer": "Do"},
            {"question": "My car ___ (consume) too much gas.", "options": ["consumes", "consume", "is consuming"], "answer": "consumes"},
            {"question": "She ___ (know) the answer to this question.", "options": ["knows", "know", "is knowing"], "answer": "knows"},
            {"question": "Vegetarians ___ (not / eat) meat.", "options": ["don't eat", "doesn't eat", "aren't eating"], "answer": "don't eat"},
            {"question": "___ it snow in your city in winter?", "options": ["Does", "Do", "Is"], "answer": "Does"},
            {"question": "Nurses ___ (help) sick people in hospitals.", "options": ["help", "helps", "are helping"], "answer": "help"},
            {"question": "He ___ (play) the guitar very well.", "options": ["plays", "play", "is playing"], "answer": "plays"},
            {"question": "Why ___ you always arrive late?", "options": ["do", "does", "are"], "answer": "do"},
            {"question": "The earth ___ (revolve) around the sun.", "options": ["revolves", "revolve", "is revolving"], "answer": "revolves"},
            {"question": "I ___ (not / understand) this rule.", "options": ["don't understand", "doesn't understand", "am not understanding"], "answer": "don't understand"},
            {"question": "___ she like reading books?", "options": ["Does", "Do", "Is"], "answer": "Does"},
            {"question": "Fast cars ___ (cost) a lot of money.", "options": ["cost", "costs", "are costing"], "answer": "cost"},
            {"question": "My father ___ (read) the newspaper every morning.", "options": ["reads", "read", "is reading"], "answer": "reads"}
        ]
    },
    "future-simple": {
        "title": "Future Simple",
        "category": "future",
        "bg_image": "https://images.unsplash.com/photo-1761497533208-010f57837863?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "formula": "Will + V1",
        "examples": ["I will write code tomorrow"],
        "color": "pink",
        "questions": [
            {"question": "I think it ___ (rain) tomorrow afternoon.", "options": ["will rain", "rains", "is raining"], "answer": "will rain"},
            {"question": "She ___ (help) you with your luggage.", "options": ["will help", "helps", "is helping"], "answer": "will help"},
            {"question": "They ___ (not / accept) our proposal.", "options": ["won't accept", "don't accept", "aren't accepting"], "answer": "won't accept"},
            {"question": "___ you come to my birthday party next week?", "options": ["Will", "Do", "Are"], "answer": "Will"},
            {"question": "We ___ (win) this game easily.", "options": ["will win", "win", "won"], "answer": "will win"},
            {"question": "He ___ (be) twenty years old next month.", "options": ["will be", "is", "was"], "answer": "will be"},
            {"question": "I promise I ___ (not / tell) anyone your secret.", "options": ["won't tell", "don't tell", "am not telling"], "answer": "won't tell"},
            {"question": "___ she remember to buy milk?", "options": ["Will", "Does", "Is"], "answer": "Will"},
            {"question": "The presentation ___ (start) in ten minutes.", "options": ["will start", "starts", "is starting"], "answer": "will start"},
            {"question": "People ___ (travel) to Mars in the future.", "options": ["will travel", "travel", "traveled"], "answer": "will travel"},
            {"question": "I ___ (call) you as soon as I arrive.", "options": ["will call", "call", "called"], "answer": "will call"},
            {"question": "Prices ___ (not / go) down anytime soon.", "options": ["won't go", "don't go", "aren't going"], "answer": "won't go"},
            {"question": "___ they support our new initiative?", "options": ["Will", "Do", "Are"], "answer": "Will"},
            {"question": "She ___ (find) a better job very soon.", "options": ["will find", "finds", "found"], "answer": "will find"},
            {"question": "We ___ (probably / visit) Paris next year.", "options": ["will probably visit", "probably visit", "visit probably"], "answer": "will probably visit"},
            {"question": "He ___ (not / pass) the exam if he doesn't study.", "options": ["won't pass", "doesn't pass", "isn't passing"], "answer": "won't pass"},
            {"question": "___ you lend me your pen for a moment?", "options": ["Will", "Do", "Can"], "answer": "Will"},
            {"question": "Technology ___ (change) our lives even more.", "options": ["will change", "changes", "changed"], "answer": "will change"},
            {"question": "I am sure everything ___ (be) fine.", "options": ["will be", "is", "was"], "answer": "will be"},
            {"question": "The sun ___ (set) at 8 PM tonight.", "options": ["will set", "sets", "is setting"], "answer": "will set"},
            {"question": "I ___ (buy) a new laptop next month.", "options": ["will buy", "buy", "bought"], "answer": "will buy"},
            {"question": "She ___ (not / agree) with your plan.", "options": ["won't agree", "doesn't agree", "isn't agreeing"], "answer": "won't agree"},
            {"question": "___ you help me with this heavy box?", "options": ["Will", "Do", "Are"], "answer": "Will"},
            {"question": "He ___ (become) a great doctor someday.", "options": ["will become", "becomes", "became"], "answer": "will become"},
            {"question": "They ___ (not / survive) without water.", "options": ["won't survive", "don't survive", "aren't surviving"], "answer": "won't survive"},
            {"question": "What ___ you do if you win the lottery?", "options": ["will", "do", "did"], "answer": "will"},
            {"question": "Our team ___ (win) the championship.", "options": ["will win", "wins", "won"], "answer": "will win"},
            {"question": "The train ___ (arrive) on platform 4.", "options": ["will arrive", "arrives", "arrived"], "answer": "will arrive"},
            {"question": "I hope she ___ (like) her present.", "options": ["will like", "likes", "liked"], "answer": "will like"},
            {"question": "Nobody ___ (know) the answer to this riddle.", "options": ["will know", "knows", "knew"], "answer": "will know"}
        ]
    },
    "past-continuous": {
        "title": "Past Continuous",
        "category": "past",
        "bg_image": "https://images.unsplash.com/photo-1643789640567-0d3f3175868d?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "formula": "Was / were + V-ing",
        "examples": ["I was writing code"],
        "color": "purple",
        "questions": [
            {"question": "I ___ (read) a book when the phone rang.", "options": ["was reading", "read", "were reading"], "answer": "was reading"},
            {"question": "They ___ (play) tennis at 5 PM yesterday.", "options": ["were playing", "was playing", "played"], "answer": "were playing"},
            {"question": "She ___ (not / sleep) when I entered the room.", "options": ["wasn't sleeping", "weren't sleeping", "didn't sleep"], "answer": "wasn't sleeping"},
            {"question": "___ you working on the project all evening?", "options": ["Were", "Was", "Did"], "answer": "Were"},
            {"question": "He ___ (drive) to work when it started to snow.", "options": ["was driving", "drove", "were driving"], "answer": "was driving"},
            {"question": "What ___ you doing at midnight last night?", "options": ["were", "was", "did"], "answer": "were"},
            {"question": "The children ___ (paint) pictures in the garden.", "options": ["were painting", "was painting", "painted"], "answer": "were painting"},
            {"question": "It ___ (rain) heavily during our walk.", "options": ["was raining", "rained", "were raining"], "answer": "was raining"},
            {"question": "She ___ (cook) dinner while he was fixing the sink.", "options": ["was cooking", "cooked", "were cooking"], "answer": "was cooking"},
            {"question": "We ___ (not / listen) to the teacher.", "options": ["weren't listening", "wasn't listening", "didn't listen"], "answer": "weren't listening"},
            {"question": "___ it raining when you left the house?", "options": ["Was", "Were", "Did"], "answer": "Was"},
            {"question": "They ___ (talk) about their trip all morning.", "options": ["were talking", "was talking", "talked"], "answer": "were talking"},
            {"question": "I ___ (wear) a jacket because it was cold.", "options": ["was wearing", "wore", "were wearing"], "answer": "was wearing"},
            {"question": "He ___ (try) to fix his computer for hours.", "options": ["was trying", "tried", "were trying"], "answer": "was trying"},
            {"question": "The dog ___ (bark) at the mailman.", "options": ["was barking", "barked", "were barking"], "answer": "was barking"},
            {"question": "___ she wearing her new red dress?", "options": ["Was", "Were", "Did"], "answer": "Was"},
            {"question": "We ___ (wait) for the bus in the cold wind.", "options": ["were waiting", "was waiting", "waited"], "answer": "were waiting"},
            {"question": "The sun ___ (shine) brightly that afternoon.", "options": ["was shining", "shone", "were shining"], "answer": "was shining"},
            {"question": "He ___ (not / pay) attention during the lecture.", "options": ["wasn't paying", "weren't paying", "didn't pay"], "answer": "wasn't paying"},
            {"question": "They ___ (travel) across Europe at this time last year.", "options": ["were traveling", "was traveling", "traveled"], "answer": "were traveling"},
            {"question": "I ___ (study) math at 8 PM yesterday.", "options": ["was studying", "studied", "were studying"], "answer": "was studying"},
            {"question": "She ___ (not / cry), she was laughing.", "options": ["wasn't crying", "weren't crying", "didn't cry"], "answer": "wasn't crying"},
            {"question": "___ you sleeping when I called you?", "options": ["Were", "Was", "Did"], "answer": "Were"},
            {"question": "The birds ___ (sing) in the trees.", "options": ["were singing", "was singing", "sang"], "answer": "were singing"},
            {"question": "He ___ (run) in the park when he lost his keys.", "options": ["was running", "ran", "were running"], "answer": "was running"},
            {"question": "What ___ they discussing at the meeting?", "options": ["were", "was", "did"], "answer": "were"},
            {"question": "We ___ (have) dinner when the lights went out.", "options": ["were having", "had", "was having"], "answer": "were having"},
            {"question": "She ___ (clean) her room all afternoon.", "options": ["was cleaning", "cleaned", "were cleaning"], "answer": "was cleaning"},
            {"question": "The wind ___ (blow) fiercely outside.", "options": ["was blowing", "blew", "were blowing"], "answer": "was blowing"},
            {"question": "I ___ (not / do) anything wrong.", "options": ["wasn't doing", "weren't doing", "didn't do"], "answer": "wasn't doing"}
        ]
    },
    "present-continuous": {
        "title": "Present Continuous",
        "category": "present",
        "bg_image": "https://images.unsplash.com/photo-1696159235420-2cc786b9bcd0?q=80&w=686&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "formula": "Am / Is / Are + V-ing",
        "examples": ["I am writing code"],
        "color": "blue",
        "questions": [
            {"question": "Look! The cat ___ (climb) up the tree.", "options": ["is climbing", "climbs", "climb"], "answer": "is climbing"},
            {"question": "Listen! Someone ___ (sing) in the hallway.", "options": ["is singing", "sings", "sing"], "answer": "is singing"},
            {"question": "We ___ (prepare) for the upcoming exam right now.", "options": ["are preparing", "prepare", "is preparing"], "answer": "are preparing"},
            {"question": "She ___ (not / work) at the moment.", "options": ["isn't working", "aren't working", "doesn't work"], "answer": "isn't working"},
            {"question": "___ you listening to me?", "options": ["Are", "Is", "Do"], "answer": "Are"},
            {"question": "They ___ (build) a new hospital downtown.", "options": ["are building", "build", "is building"], "answer": "are building"},
            {"question": "Why ___ you wearing a coat indoors?", "options": ["are", "is", "do"], "answer": "are"},
            {"question": "He ___ (stay) with his relatives this week.", "options": ["is staying", "stays", "stay"], "answer": "is staying"},
            {"question": "The baby ___ (sleep), please be quiet.", "options": ["is sleeping", "sleeps", "sleep"], "answer": "is sleeping"},
            {"question": "I ___ (read) an incredible science fiction novel.", "options": ["am reading", "read", "is reading"], "answer": "am reading"},
            {"question": "It ___ (get) colder and colder every day.", "options": ["is getting", "gets", "get"], "answer": "is getting"},
            {"question": "You ___ (always / interrupt) me when I talk!", "options": ["are always interrupting", "always interrupt", "always interrupting"], "answer": "are always interrupting"},
            {"question": "She ___ (not / wear) glasses today.", "options": ["isn't wearing", "aren't wearing", "doesn't wear"], "answer": "isn't wearing"},
            {"question": "___ your brother looking for a job?", "options": ["Is", "Are", "Does"], "answer": "Is"},
            {"question": "We ___ (have) dinner at a fancy restaurant tonight.", "options": ["are having", "have", "is having"], "answer": "are having"},
            {"question": "The wind ___ (blow) very strongly outside.", "options": ["is blowing", "blows", "blow"], "answer": "is blowing"},
            {"question": "They ___ (not / play) football right now.", "options": ["aren't playing", "isn't playing", "don't play"], "answer": "aren't playing"},
            {"question": "What ___ you doing at the computer?", "options": ["are", "is", "do"], "answer": "are"},
            {"question": "Prices of electronics ___ (go) up again.", "options": ["are going", "go", "is going"], "answer": "are going"},
            {"question": "He ___ (learn) to play the guitar this month.", "options": ["is learning", "learns", "learn"], "answer": "is learning"},
            {"question": "Look at the sky! It ___ (snow).", "options": ["is snowing", "snows", "snow"], "answer": "is snowing"},
            {"question": "I ___ (wait) for my friend right now.", "options": ["am waiting", "wait", "is waiting"], "answer": "am waiting"},
            {"question": "She ___ (not / pay) attention to the lesson.", "options": ["isn't paying", "aren't paying", "doesn't pay"], "answer": "isn't paying"},
            {"question": "___ they running in the marathon?", "options": ["Are", "Is", "Do"], "answer": "Are"},
            {"question": "The chef ___ (prepare) a special meal.", "options": ["is preparing", "prepares", "prepare"], "answer": "is preparing"},
            {"question": "Why ___ you crying?", "options": ["are", "is", "do"], "answer": "are"},
            {"question": "We ___ (sit) in the living room.", "options": ["are sitting", "sit", "is sitting"], "answer": "are sitting"},
            {"question": "The sun ___ (shine) brightly today.", "options": ["is shining", "shines", "shine"], "answer": "is shining"},
            {"question": "He ___ (not / do) anything right now.", "options": ["isn't doing", "aren't doing", "doesn't do"], "answer": "isn't doing"},
            {"question": "___ she wearing a jacket?", "options": ["Is", "Are", "Does"], "answer": "Is"}
        ]
    },
    "future-continuous": {
        "title": "Future Continuous",
        "category": "future",
        "bg_image": "https://images.unsplash.com/photo-1762158144296-7097a5625512?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "formula": "Will + be + V-ing",
        "examples": ["I will be writing code"],
        "color": "pink",
        "questions": [
            {"question": "Tomorrow at 8 PM I ___ (write) code.", "options": ["will be writing", "will write", "am writing"], "answer": "will be writing"},
            {"question": "This time next week we ___ (travel) to London.", "options": ["will be traveling", "will travel", "are traveling"], "answer": "will be traveling"},
            {"question": "She ___ (not / work) when you arrive.", "options": ["won't be working", "won't work", "isn't working"], "answer": "won't be working"},
            {"question": "___ you be using your laptop tomorrow morning?", "options": ["Will", "Do", "Are"], "answer": "Will"},
            {"question": "At midnight, they ___ (sleep) soundly.", "options": ["will be sleeping", "will sleep", "are sleeping"], "answer": "will be sleeping"},
            {"question": "He ___ (give) a speech at the conference this time tomorrow.", "options": ["will be giving", "will give", "gives"], "answer": "will be giving"},
            {"question": "I ___ (wait) for you at the station when your train pulls in.", "options": ["will be waiting", "will wait", "wait"], "answer": "will be waiting"},
            {"question": "What ___ you be doing in five years?", "options": ["will", "do", "are"], "answer": "will"},
            {"question": "The band ___ (perform) live hits all evening.", "options": ["will be performing", "will perform", "perform"], "answer": "will be performing"},
            {"question": "She ___ (not / sleep) at that late hour.", "options": ["won't be sleeping", "won't sleep", "isn't sleeping"], "answer": "won't be sleeping"},
            {"question": "___ it be raining when we land in Kyiv?", "options": ["Will", "Does", "Is"], "answer": "Will"},
            {"question": "We ___ (celebrate) our anniversary all weekend.", "options": ["will be celebrating", "will celebrate", "celebrate"], "answer": "will be celebrating"},
            {"question": "He ___ (drive) across the country during the holiday.", "options": ["will be driving", "will drive", "drives"], "answer": "will be driving"},
            {"question": "They ___ (not / use) the office on Sunday.", "options": ["won't be using", "won't use", "aren't using"], "answer": "won't be using"},
            {"question": "___ she be wearing her graduation gown tomorrow?", "options": ["Will", "Is", "Does"], "answer": "Will"},
            {"question": "I ___ (study) in the library all afternoon.", "options": ["will be studying", "will study", "study"], "answer": "will be studying"},
            {"question": "The kids ___ (play) outside while we cook.", "options": ["will be playing", "will play", "play"], "answer": "will be playing"},
            {"question": "By this time tomorrow, I ___ (fly) over the ocean.", "options": ["will be flying", "will fly", "am flying"], "answer": "will be flying"},
            {"question": "Why ___ you be wearing a suit tomorrow?", "options": ["will", "do", "are"], "answer": "will"},
            {"question": "He ___ (rest) at home all day long.", "options": ["will be resting", "will rest", "rests"], "answer": "will be resting"},
            {"question": "At 10 AM tomorrow, I ___ (attend) a meeting.", "options": ["will be attending", "will attend", "attend"], "answer": "will be attending"},
            {"question": "She ___ (not / cook) when you come over.", "options": ["won't be cooking", "won't cook", "isn't cooking"], "answer": "won't be cooking"},
            {"question": "___ you be needing your car tomorrow?", "options": ["Will", "Do", "Are"], "answer": "Will"},
            {"question": "They ___ (build) our new house next month.", "options": ["will be building", "will build", "build"], "answer": "will be building"},
            {"question": "I ___ (sit) on the beach this time next week.", "options": ["will be sitting", "will sit", "sit"], "answer": "will be sitting"},
            {"question": "What ___ you be wearing at the party?", "options": ["will", "do", "are"], "answer": "will"},
            {"question": "We ___ (watch) the match all evening.", "options": ["will be watching", "will watch", "watch"], "answer": "will be watching"},
            {"question": "He ___ (work) on the project the whole night.", "options": ["will be working", "will work", "works"], "answer": "will be working"},
            {"question": "The sun ___ (shine) brightly all day tomorrow.", "options": ["will be shining", "will shine", "shines"], "answer": "will be shining"},
            {"question": "I ___ (not / sleep) when you call me late.", "options": ["won't be sleeping", "won't sleep", "am not sleeping"], "answer": "won't be sleeping"}
        ]
    },
    "past-perfect": {
        "title": "Past Perfect",
        "category": "past",
        "bg_image": "https://images.unsplash.com/photo-1667159321939-8bb2b849cd34?q=80&w=1072&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "formula": "Had + V3/-ed",
        "examples": ["He had gone"],
        "color": "purple",
        "questions": [
            {"question": "By the time we arrived, the train ___ (leave).", "options": ["had left", "left", "has left"], "answer": "had left"},
            {"question": "She ___ (already / finish) her homework before mom asked.", "options": ["had already finished", "already finished", "has already finished"], "answer": "had already finished"},
            {"question": "They ___ (not / eat) anything before the long journey.", "options": ["hadn't eaten", "didn't eat", "haven't eaten"], "answer": "hadn't eaten"},
            {"question": "___ you ever visited London before last year?", "options": ["Had", "Have", "Did"], "answer": "Had"},
            {"question": "He realized he ___ (forget) his keys at home.", "options": ["had forgotten", "forgot", "has forgotten"], "answer": "had forgotten"},
            {"question": "The garden was dry because it ___ (not / rain) for weeks.", "options": ["hadn't rained", "didn't rain", "hasn't rained"], "answer": "hadn't rained"},
            {"question": "She ___ (meet) him once before the party.", "options": ["had met", "met", "has met"], "answer": "had met"},
            {"question": "What ___ you done before the police arrived?", "options": ["had", "have", "did"], "answer": "had"},
            {"question": "The film ___ (start) when we found our seats.", "options": ["had started", "started", "has started"], "answer": "had started"},
            {"question": "I ___ (never / see) such a beautiful sunset before that day.", "options": ["had never seen", "never saw", "have never seen"], "answer": "had never seen"},
            {"question": "They ___ (buy) tickets before the box office closed.", "options": ["had bought", "bought", "have bought"], "answer": "had bought"},
            {"question": "He ___ (not / read) the book, so he didn't understand the movie.", "options": ["hadn't read", "didn't read", "hasn't read"], "answer": "hadn't read"}
        ]
    },
    "present-perfect": {
        "title": "Present Perfect",
        "category": "present",
        "bg_image": "https://images.unsplash.com/photo-1705769944228-2ea309059e0f?q=80&w=627&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "formula": "have/has + V3 (ed)",
        "affirmative": "have/has + V3",
        "negative": "haven't/hasn't + V3",
        "question": "Have/Has + subject + V3",
        "examples": ["I have already finished my project."],
        "description": "Дія завершилася до теперішнього часу, і важливий результат.",
        "usage": ["Результат на обличчя", "Життєвий досвід"],
        "keywords": ["already", "just", "yet", "ever", "never"],
        "color": "blue",
        "questions": []
    },
    "present-perfect-continuous": {
        "title": "Present Perfect Continuous",
        "category": "present",
        "bg_image": "https://images.unsplash.com/photo-1603029025879-df1f320b2fb1?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "formula": "have/has been + V-ing",
        "affirmative": "have/has been + V-ing",
        "negative": "haven't/hasn't been + V-ing",
        "question": "Have/Has + subject + been + V-ing",
        "examples": ["I have been coding for 3 hours."],
        "description": "Дія почалася в минулому і триває досі.",
        "usage": ["Тривала дія, що триває зараз"],
        "keywords": ["for", "since", "all day"],
        "color": "blue",
        "questions": []
    },
    "past-perfect-continuous": {
        "title": "Past Perfect Continuous",
        "category": "past",
        "bg_image": "https://images.unsplash.com/photo-1445998559126-132150395033?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "formula": "had been + V-ing",
        "affirmative": "had been + V-ing",
        "negative": "hadn't been + V-ing",
        "question": "Had + subject + been + V-ing",
        "examples": ["I had been coding for 2 hours before he came."],
        "description": "Тривала дія, що тривала певний час до іншого моменту в минулому.",
        "usage": ["Тривалість до минулої події"],
        "keywords": ["for", "since", "until"],
        "color": "purple",
        "questions": []
    },
    "future-perfect": {
        "title": "Future Perfect",
        "category": "future",
        "bg_image": "https://images.unsplash.com/photo-1765199829137-f05c0dc3025a?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "formula": "will have + V3",
        "affirmative": "will have + V3",
        "negative": "won't have + V3",
        "question": "Will + subject + have + V3",
        "examples": ["I will have finished this code by 5 PM."],
        "description": "Дія, що завершиться до визначеного моменту в майбутньому.",
        "usage": ["Результат у майбутньому"],
        "keywords": ["by tomorrow", "by 5 o'clock"],
        "color": "pink",
        "questions": []
    },
    "future-perfect-continuous": {
        "title": "Future Perfect Continuous",
        "category": "future",
        "bg_image": "https://images.unsplash.com/photo-1572860929478-e8b3c27dfcf4?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "formula": "will have been + V-ing",
        "affirmative": "will have been + V-ing",
        "negative": "won't have been + V-ing",
        "question": "Will + subject + have been + V-ing",
        "examples": ["I will have been coding for 5 hours by noon."],
        "description": "Тривала дія, що почнеться і триватиме певний час до моменту в майбутньому.",
        "usage": ["Тривалість до майбутньої події"],
        "keywords": ["for 5 hours by", "since"],
        "color": "pink",
        "questions": []
    }
}