GRAMMAR_DATA = {
        "past-simple": {
        "title": "Past Simple",
        "category": "past",
        "formula": "Did / didn't + V2/-ed",
        "card_formula": "V2 — друга форма з таблиці неправильних дієслів або закінчення -ed",

        # Додаємо нові поля для форм:
        "affirmative": "I/You/He/She/It/We/They +V2 /-ed",
        "negative": "Did + not + V1 (didn't + V1)",
        "question": "Did + I / you / he... + V1?",

        "examples": [
            "I wrote code yesterday (+) ",
            "She visited her grandparents (+) ",
            "They didn't play football (-) ",
            "He didn't watch a movie (-) ",
            "Did you code yesterday (?) ",
            "Did she visit them (?) "
        ],
        "description": "Використовується для дій, які завершилися в минулому в конкретний час.",
        "usage": [
            "Дія, яка сталася в минулому і вже закінчилася",
            "Послідовність дій у минулому"
        ],
        "keywords": [
            "yesterday (вчора)",
            "last week / month (минулого тижня / місяця)",
            "ago (тому)"
        ],
        "color": "purple",
        "questions": [
            {"question": "I ___ (write) a letter to my friend yesterday.", "options": ["wrote", "write", "had written"],
             "answer": "wrote"},
            {"question": "She ___ (go) to the supermarket an hour ago.", "options": ["went", "goed", "goes"],
             "answer": "went"},
            {"question": "They ___ (play) football last Sunday.", "options": ["played", "play", "were playing"],
             "answer": "played"},
            {"question": "He ___ (not / buy) a new car last month.",
             "options": ["didn't buy", "doesn't buy", "wasn't buying"], "answer": "didn't buy"},
            {"question": "___ you see that movie on TV last night?", "options": ["Did", "Do", "Were"], "answer": "Did"},
            {"question": "We ___ (be) very tired after the trip.", "options": ["were", "was", "are"], "answer": "were"},
            {"question": "She ___ (cook) a delicious dinner yesterday.", "options": ["cooked", "cooks", "has cooked"],
             "answer": "cooked"},
            {"question": "What time ___ you wake up this morning?", "options": ["did", "do", "were"], "answer": "did"},
            {"question": "The train ___ (arrive) ten minutes late.", "options": ["arrived", "arrive", "has arrived"],
             "answer": "arrived"},
            {"question": "I ___ (not / know) the answer to the test question.",
             "options": ["didn't know", "don't know", "wasn't knowing"], "answer": "didn't know"},
            {"question": "He ___ (read) an interesting book last week.", "options": ["read", "reads", "is reading"],
             "answer": "read"},
            {"question": "Where ___ they spend their summer vacation?", "options": ["did", "do", "were"],
             "answer": "did"},
            {"question": "The dog ___ (bark) all night long.", "options": ["barked", "barks", "bark"],
             "answer": "barked"},
            {"question": "She ___ (meet) her old school friend downtown.", "options": ["met", "meet", "has met"],
             "answer": "met"},
            {"question": "It ___ (start) to rain while we were walking.",
             "options": ["started", "starts", "was starting"], "answer": "started"},
            {"question": "We ___ (clean) the whole house on Saturday.", "options": ["cleaned", "clean", "have cleaned"],
             "answer": "cleaned"},
            {"question": "Why ___ you cry during the movie?", "options": ["did", "do", "were"], "answer": "did"},
            {"question": "He ___ (lose) his keys at the office.", "options": ["lost", "lose", "losed"],
             "answer": "lost"},
            {"question": "They ___ (sell) their old house last year.", "options": ["sold", "sells", "have sold"],
             "answer": "sold"},
            {"question": "I ___ (forget) to call you yesterday.", "options": ["forgot", "forget", "have forgotten"],
             "answer": "forgot"},
            {"question": "She ___ (paint) this picture in 2015.", "options": ["painted", "paint", "has painted"],
             "answer": "painted"},
            {"question": "___ you enjoy the party last weekend?", "options": ["Did", "Do", "Were"], "answer": "Did"},
            {"question": "We ___ (not / spend) much money on the trip.",
             "options": ["didn't spend", "don't spend", "weren't spending"], "answer": "didn't spend"},
            {"question": "He ___ (catch) a big fish in the river.", "options": ["caught", "catched", "catch"],
             "answer": "caught"},
            {"question": "The wind ___ (blow) our garden fence down.", "options": ["blew", "blowed", "blown"],
             "answer": "blew"},
            {"question": "Who ___ you talk to after the meeting?", "options": ["did", "do", "were"], "answer": "did"},
            {"question": "She ___ (wear) her best dress to the gala.", "options": ["wore", "weared", "worn"],
             "answer": "wore"},
            {"question": "They ___ (build) this bridge centuries ago.", "options": ["built", "builded", "have built"],
             "answer": "built"},
            {"question": "I ___ (find) a wallet on the street.", "options": ["found", "find", "founded"],
             "answer": "found"},
            {"question": "The teacher ___ (explain) the grammar rule clearly.",
             "options": ["explained", "explain", "was explaining"], "answer": "explained"}
        ]
    },
    "present-simple": {
        "title": "Present Simple",
        "category": "present",
        "formula": "Do / does + V1",
        "examples": ["I write code"],
        "color": "blue",
        "questions": [
            {"question": "She ___ (work) as a designer in a local company.", "options": ["works", "work", "is working"],
             "answer": "works"},
            {"question": "They ___ (not / like) to wake up early on Sundays.",
             "options": ["don't like", "doesn't like", "aren't liking"], "answer": "don't like"},
            {"question": "___ your friend live in this neighborhood?", "options": ["Does", "Do", "Is"],
             "answer": "Does"},
            {"question": "Water ___ (boil) at 100 degrees Celsius.", "options": ["boils", "boil", "is boiling"],
             "answer": "boils"},
            {"question": "I usually ___ (drink) coffee in the morning.", "options": ["drink", "drinks", "am drinking"],
             "answer": "drink"},
            {"question": "He ___ (not / play) tennis on weekdays.",
             "options": ["doesn't play", "don't play", "isn't playing"], "answer": "doesn't play"},
            {"question": "___ you speak English fluently?", "options": ["Do", "Does", "Are"], "answer": "Do"},
            {"question": "The sun ___ (rise) in the east.", "options": ["rises", "rise", "is rising"],
             "answer": "rises"},
            {"question": "My parents ___ (live) in a big house.", "options": ["live", "lives", "are living"],
             "answer": "live"},
            {"question": "Cats ___ (hate) getting wet in the rain.", "options": ["hate", "hates", "are hating"],
             "answer": "hate"},
            {"question": "She ___ (study) Spanish at university.", "options": ["studies", "study", "is studying"],
             "answer": "studies"},
            {"question": "We ___ (not / watch) TV very often.",
             "options": ["don't watch", "doesn't watch", "aren't watching"], "answer": "don't watch"},
            {"question": "___ your brother have a driving license?", "options": ["Does", "Do", "Has"],
             "answer": "Does"},
            {"question": "Good students ___ (do) their homework regularly.", "options": ["do", "does", "are doing"],
             "answer": "do"},
            {"question": "The bank ___ (open) at 9:00 AM every day.", "options": ["opens", "open", "is opening"],
             "answer": "opens"},
            {"question": "He ___ (always / help) his friends in trouble.",
             "options": ["always helps", "always help", "is always helping"], "answer": "always helps"},
            {"question": "They ___ (not / eat) fast food.", "options": ["don't eat", "doesn't eat", "aren't eating"],
             "answer": "don't eat"},
            {"question": "___ birds migrate south for the winter?", "options": ["Do", "Does", "Are"], "answer": "Do"},
            {"question": "My car ___ (consume) too much gas.", "options": ["consumes", "consume", "is consuming"],
             "answer": "consumes"},
            {"question": "She ___ (know) the answer to this question.", "options": ["knows", "know", "is knowing"],
             "answer": "knows"},
            {"question": "Vegetarians ___ (not / eat) meat.", "options": ["don't eat", "doesn't eat", "aren't eating"],
             "answer": "don't eat"},
            {"question": "___ it snow in your city in winter?", "options": ["Does", "Do", "Is"], "answer": "Does"},
            {"question": " Nurses ___ (help) sick people in hospitals.", "options": ["help", "helps", "are helping"],
             "answer": "help"},
            {"question": "He ___ (play) the guitar very well.", "options": ["plays", "play", "is playing"],
             "answer": "plays"},
            {"question": "Why ___ you always arrive late?", "options": ["do", "does", "are"], "answer": "do"},
            {"question": "The earth ___ (revolve) around the sun.", "options": ["revolves", "revolve", "is revolving"],
             "answer": "revolves"},
            {"question": "I ___ (not / understand) this rule.",
             "options": ["don't understand", "doesn't understand", "am not understanding"],
             "answer": "don't understand"},
            {"question": "___ she like reading books?", "options": ["Does", "Do", "Is"], "answer": "Does"},
            {"question": "Fast cars ___ (cost) a lot of money.", "options": ["cost", "costs", "are costing"],
             "answer": "cost"},
            {"question": "My father ___ (read) the newspaper every morning.",
             "options": ["reads", "read", "is reading"], "answer": "reads"}
        ]
    },
    "future-simple": {
        "title": "Future Simple",
        "category": "future",
        "formula": "Will + V1",
        "examples": ["I will write code tomorrow"],
        "color": "pink",
        "questions": [
            {"question": "I think it ___ (rain) tomorrow afternoon.", "options": ["will rain", "rains", "is raining"],
             "answer": "will rain"},
            {"question": "She ___ (help) you with your luggage.", "options": ["will help", "helps", "is helping"],
             "answer": "will help"},
            {"question": "They ___ (not / accept) our proposal.",
             "options": ["won't accept", "don't accept", "aren't accepting"], "answer": "won't accept"},
            {"question": "___ you come to my birthday party next week?", "options": ["Will", "Do", "Are"],
             "answer": "Will"},
            {"question": "We ___ (win) this game easily.", "options": ["will win", "win", "won"], "answer": "will win"},
            {"question": "He ___ (be) twenty years old next month.", "options": ["will be", "is", "was"],
             "answer": "will be"},
            {"question": "I promise I ___ (not / tell) anyone your secret.",
             "options": ["won't tell", "don't tell", "am not telling"], "answer": "won't tell"},
            {"question": "___ she remember to buy milk?", "options": ["Will", "Does", "Is"], "answer": "Will"},
            {"question": "The presentation ___ (start) in ten minutes.",
             "options": ["will start", "starts", "is starting"], "answer": "will start"},
            {"question": "People ___ (travel) to Mars in the future.", "options": ["will travel", "travel", "traveled"],
             "answer": "will travel"},
            {"question": "I ___ (call) you as soon as I arrive.", "options": ["will call", "call", "called"],
             "answer": "will call"},
            {"question": "Prices ___ (not / go) down anytime soon.",
             "options": ["won't go", "don't go", "aren't going"], "answer": "won't go"},
            {"question": "___ they support our new initiative?", "options": ["Will", "Do", "Are"], "answer": "Will"},
            {"question": "She ___ (find) a better job very soon.", "options": ["will find", "finds", "found"],
             "answer": "will find"},
            {"question": "We ___ (probably / visit) Paris next year.",
             "options": ["will probably visit", "probably visit", "visit probably"], "answer": "will probably visit"},
            {"question": "He ___ (not / pass) the exam if he doesn't study.",
             "options": ["won't pass", "doesn't pass", "isn't passing"], "answer": "won't pass"},
            {"question": "___ you lend me your pen for a moment?", "options": ["Will", "Do", "Can"], "answer": "Will"},
            {"question": "Technology ___ (change) our lives even more.",
             "options": ["will change", "changes", "changed"], "answer": "will change"},
            {"question": "I am sure everything ___ (be) fine.", "options": ["will be", "is", "was"],
             "answer": "will be"},
            {"question": "The sun ___ (set) at 8 PM tonight.", "options": ["will set", "sets", "is setting"],
             "answer": "will set"},
            {"question": "I ___ (buy) a new laptop next month.", "options": ["will buy", "buy", "bought"],
             "answer": "will buy"},
            {"question": "She ___ (not / agree) with your plan.",
             "options": ["won't agree", "doesn't agree", "isn't agreeing"], "answer": "won't agree"},
            {"question": "___ you help me with this heavy box?", "options": ["Will", "Do", "Are"], "answer": "Will"},
            {"question": "He ___ (become) a great doctor someday.", "options": ["will become", "becomes", "became"],
             "answer": "will become"},
            {"question": "They ___ (not / survive) without water.",
             "options": ["won't survive", "don't survive", "aren't surviving"], "answer": "won't survive"},
            {"question": "What ___ you do if you win the lottery?", "options": ["will", "do", "did"], "answer": "will"},
            {"question": "Our team ___ (win) the championship.", "options": ["will win", "wins", "won"],
             "answer": "will win"},
            {"question": "The train ___ (arrive) on platform 4.", "options": ["will arrive", "arrives", "arrived"],
             "answer": "will arrive"},
            {"question": "I hope she ___ (like) her present.", "options": ["will like", "likes", "liked"],
             "answer": "will like"},
            {"question": "Nobody ___ (know) the answer to this riddle.", "options": ["will know", "knows", "knew"],
             "answer": "will know"}
        ]
    },
    "past-continuous": {
        "title": "Past Continuous",
        "category": "past",
        "formula": "Was / were + V-ing",
        "examples": ["I was writing code"],
        "color": "purple",
        "questions": [
            {"question": "I ___ (read) a book when the phone rang.", "options": ["was reading", "read", "were reading"],
             "answer": "was reading"},
            {"question": "They ___ (play) tennis at 5 PM yesterday.",
             "options": ["were playing", "was playing", "played"], "answer": "were playing"},
            {"question": "She ___ (not / sleep) when I entered the room.",
             "options": ["wasn't sleeping", "weren't sleeping", "didn't sleep"], "answer": "wasn't sleeping"},
            {"question": "___ you working on the project all evening?", "options": ["Were", "Was", "Did"],
             "answer": "Were"},
            {"question": "He ___ (drive) to work when it started to snow.",
             "options": ["was driving", "drove", "were driving"], "answer": "was driving"},
            {"question": "What ___ you doing at midnight last night?", "options": ["were", "was", "did"],
             "answer": "were"},
            {"question": "The children ___ (paint) pictures in the garden.",
             "options": ["were painting", "was painting", "painted"], "answer": "were painting"},
            {"question": "It ___ (rain) heavily during our walk.", "options": ["was raining", "rained", "were raining"],
             "answer": "was raining"},
            {"question": "She ___ (cook) dinner while he was fixing the sink.",
             "options": ["was cooking", "cooked", "were cooking"], "answer": "was cooking"},
            {"question": "We ___ (not / listen) to the teacher.",
             "options": ["weren't listening", "wasn't listening", "didn't listen"], "answer": "weren't listening"},
            {"question": "___ it raining when you left the house?", "options": ["Was", "Were", "Did"], "answer": "Was"},
            {"question": "They ___ (talk) about their trip all morning.",
             "options": ["were talking", "was talking", "talked"], "answer": "were talking"},
            {"question": "I ___ (wear) a jacket because it was cold.",
             "options": ["was wearing", "wore", "were wearing"], "answer": "was wearing"},
            {"question": "He ___ (try) to fix his computer for hours.",
             "options": ["was trying", "tried", "were trying"], "answer": "was trying"},
            {"question": "The dog ___ (bark) at the mailman.", "options": ["was barking", "barked", "were barking"],
             "answer": "was barking"},
            {"question": "___ she wearing her new red dress?", "options": ["Was", "Were", "Did"], "answer": "Was"},
            {"question": "We ___ (wait) for the bus in the cold wind.",
             "options": ["were waiting", "was waiting", "waited"], "answer": "were waiting"},
            {"question": "The sun ___ (shine) brightly that afternoon.",
             "options": ["was shining", "shone", "were shining"], "answer": "was shining"},
            {"question": "He ___ (not / pay) attention during the lecture.",
             "options": ["wasn't paying", "weren't paying", "didn't pay"], "answer": "wasn't paying"},
            {"question": "They ___ (travel) across Europe at this time last year.",
             "options": ["were traveling", "was traveling", "traveled"], "answer": "were traveling"},
            {"question": "I ___ (study) math at 8 PM yesterday.",
             "options": ["was studying", "studied", "were studying"], "answer": "was studying"},
            {"question": "She ___ (not / cry), she was laughing.",
             "options": ["wasn't crying", "weren't crying", "didn't cry"], "answer": "wasn't crying"},
            {"question": "___ you sleeping when I called you?", "options": ["Were", "Was", "Did"], "answer": "Were"},
            {"question": "The birds ___ (sing) in the trees.", "options": ["were singing", "was singing", "sang"],
             "answer": "were singing"},
            {"question": "He ___ (run) in the park when he lost his keys.",
             "options": ["was running", "ran", "were running"], "answer": "was running"},
            {"question": "What ___ they discussing at the meeting?", "options": ["were", "was", "did"],
             "answer": "were"},
            {"question": "We ___ (have) dinner when the lights went out.",
             "options": ["were having", "had", "was having"], "answer": "were having"},
            {"question": "She ___ (clean) her room all afternoon.",
             "options": ["was cleaning", "cleaned", "were cleaning"], "answer": "was cleaning"},
            {"question": "The wind ___ (blow) fiercely outside.", "options": ["was blowing", "blew", "were blowing"],
             "answer": "was blowing"},
            {"question": "I ___ (not / do) anything wrong.", "options": ["wasn't doing", "weren't doing", "didn't do"],
             "answer": "wasn't doing"}
        ]
    },
    "present-continuous": {
        "title": "Present Continuous",
        "category": "present",
        "formula": "Am / Is / Are + V-ing",
        "examples": ["I am writing code"],
        "color": "blue",
        "questions": [
            {"question": "Look! The cat ___ (climb) up the tree.", "options": ["is climbing", "climbs", "climb"],
             "answer": "is climbing"},
            {"question": "Listen! Someone ___ (sing) in the hallway.", "options": ["is singing", "sings", "sing"],
             "answer": "is singing"},
            {"question": "We ___ (prepare) for the upcoming exam right now.",
             "options": ["are preparing", "prepare", "is preparing"], "answer": "are preparing"},
            {"question": "She ___ (not / work) at the moment.",
             "options": ["isn't working", "aren't working", "doesn't work"], "answer": "isn't working"},
            {"question": "___ you listening to me?", "options": ["Are", "Is", "Do"], "answer": "Are"},
            {"question": "They ___ (build) a new hospital downtown.",
             "options": ["are building", "build", "is building"], "answer": "are building"},
            {"question": "Why ___ you wearing a coat indoors?", "options": ["are", "is", "do"], "answer": "are"},
            {"question": "He ___ (stay) with his relatives this week.", "options": ["is staying", "stays", "stay"],
             "answer": "is staying"},
            {"question": "The baby ___ (sleep), please be quiet.", "options": ["is sleeping", "sleeps", "sleep"],
             "answer": "is sleeping"},
            {"question": "I ___ (read) an incredible science fiction novel.",
             "options": ["am reading", "read", "is reading"], "answer": "am reading"},
            {"question": "It ___ (get) colder and colder every day.", "options": ["is getting", "gets", "get"],
             "answer": "is getting"},
            {"question": "You ___ (always / interrupt) me when I talk!",
             "options": ["are always interrupting", "always interrupt", "always interrupting"],
             "answer": "are always interrupting"},
            {"question": "She ___ (not / wear) glasses today.",
             "options": ["isn't wearing", "aren't wearing", "doesn't wear"], "answer": "isn't wearing"},
            {"question": "___ your brother looking for a job?", "options": ["Is", "Are", "Does"], "answer": "Is"},
            {"question": "We ___ (have) dinner at a fancy restaurant tonight.",
             "options": ["are having", "have", "is having"], "answer": "are having"},
            {"question": "The wind ___ (blow) very strongly outside.", "options": ["is blowing", "blows", "blow"],
             "answer": "is blowing"},
            {"question": "They ___ (not / play) football right now.",
             "options": ["aren't playing", "isn't playing", "don't play"], "answer": "aren't playing"},
            {"question": "What ___ you doing at the computer?", "options": ["are", "is", "do"], "answer": "are"},
            {"question": "Prices of electronics ___ (go) up again.", "options": ["are going", "go", "is going"],
             "answer": "are going"},
            {"question": "He ___ (learn) to play the guitar this month.", "options": ["is learning", "learns", "learn"],
             "answer": "is learning"},
            {"question": "Look at the sky! It ___ (snow).", "options": ["is snowing", "snows", "snow"],
             "answer": "is snowing"},
            {"question": "I ___ (wait) for my friend right now.", "options": ["am waiting", "wait", "is waiting"],
             "answer": "am waiting"},
            {"question": "She ___ (not / pay) attention to the lesson.",
             "options": ["isn't paying", "aren't paying", "doesn't pay"], "answer": "isn't paying"},
            {"question": "___ they running in the marathon?", "options": ["Are", "Is", "Do"], "answer": "Are"},
            {"question": "The chef ___ (prepare) a special meal.", "options": ["is preparing", "prepares", "prepare"],
             "answer": "is preparing"},
            {"question": "Why ___ you crying?", "options": ["are", "is", "do"], "answer": "are"},
            {"question": "We ___ (sit) in the living room.", "options": ["are sitting", "sit", "is sitting"],
             "answer": "are sitting"},
            {"question": "The sun ___ (shine) brightly today.", "options": ["is shining", "shines", "shine"],
             "answer": "is shining"},
            {"question": "He ___ (not / do) anything right now.",
             "options": ["isn't doing", "aren't doing", "doesn't do"], "answer": "isn't doing"},
            {"question": "___ she wearing a jacket?", "options": ["Is", "Are", "Does"], "answer": "Is"}
        ]
    },
    "future-continuous": {
        "title": "Future Continuous",
        "category": "future",
        "formula": "Will + be + V-ing",
        "examples": ["I will be writing code"],
        "color": "pink",
        "questions": [
            {"question": "Tomorrow at 8 PM I ___ (write) code.",
             "options": ["will be writing", "will write", "am writing"], "answer": "will be writing"},
            {"question": "This time next week we ___ (travel) to London.",
             "options": ["will be traveling", "will travel", "are traveling"], "answer": "will be traveling"},
            {"question": "She ___ (not / work) when you arrive.",
             "options": ["won't be working", "won't work", "isn't working"], "answer": "won't be working"},
            {"question": "___ you be using your laptop tomorrow morning?", "options": ["Will", "Do", "Are"],
             "answer": "Will"},
            {"question": "At midnight, they ___ (sleep) soundly.",
             "options": ["will be sleeping", "will sleep", "are sleeping"], "answer": "will be sleeping"},
            {"question": "He ___ (give) a speech at the conference this time tomorrow.",
             "options": ["will be giving", "will give", "gives"], "answer": "will be giving"},
            {"question": "I ___ (wait) for you at the station when your train pulls in.",
             "options": ["will be waiting", "will wait", "wait"], "answer": "will be waiting"},
            {"question": "What ___ you be doing in five years?", "options": ["will", "do", "are"], "answer": "will"},
            {"question": "The band ___ (perform) live hits all evening.",
             "options": ["will be performing", "will perform", "perform"], "answer": "will be performing"},
            {"question": "She ___ (not / sleep) at that late hour.",
             "options": ["won't be sleeping", "won't sleep", "isn't sleeping"], "answer": "won't be sleeping"},
            {"question": "___ it be raining when we land in Kyiv?", "options": ["Will", "Does", "Is"],
             "answer": "Will"},
            {"question": "We ___ (celebrate) our anniversary all weekend.",
             "options": ["will be celebrating", "will celebrate", "celebrate"], "answer": "will be celebrating"},
            {"question": "He ___ (drive) across the country during the holiday.",
             "options": ["will be driving", "will drive", "drives"], "answer": "will be driving"},
            {"question": "They ___ (not / use) the office on Sunday.",
             "options": ["won't be using", "won't use", "aren't using"], "answer": "won't be using"},
            {"question": "___ she be wearing her graduation gown tomorrow?", "options": ["Will", "Is", "Does"],
             "answer": "Will"},
            {"question": "I ___ (study) in the library all afternoon.",
             "options": ["will be studying", "will study", "study"], "answer": "will be studying"},
            {"question": "The kids ___ (play) outside while we cook.",
             "options": ["will be playing", "will play", "play"], "answer": "will be playing"},
            {"question": "By this time tomorrow, I ___ (fly) over the ocean.",
             "options": ["will be flying", "will fly", "am flying"], "answer": "will be flying"},
            {"question": "Why ___ you be wearing a suit tomorrow?", "options": ["will", "do", "are"], "answer": "will"},
            {"question": "He ___ (rest) at home all day long.", "options": ["will be resting", "will rest", "rests"],
             "answer": "will be resting"},
            {"question": "At 10 AM tomorrow, I ___ (attend) a meeting.",
             "options": ["will be attending", "will attend", "attend"], "answer": "will be attending"},
            {"question": "She ___ (not / cook) when you come over.",
             "options": ["won't be cooking", "won't cook", "isn't cooking"], "answer": "won't be cooking"},
            {"question": "___ you be needing your car tomorrow?", "options": ["Will", "Do", "Are"], "answer": "Will"},
            {"question": "They ___ (build) our new house next month.",
             "options": ["will be building", "will build", "build"], "answer": "will be building"},
            {"question": "I ___ (sit) on the beach this time next week.",
             "options": ["will be sitting", "will sit", "sit"], "answer": "will be sitting"},
            {"question": "What ___ you be wearing at the party?", "options": ["will", "do", "are"], "answer": "will"},
            {"question": "We ___ (watch) the match all evening.",
             "options": ["will be watching", "will watch", "watch"], "answer": "will be watching"},
            {"question": "He ___ (work) on the project the whole night.",
             "options": ["will be working", "will work", "works"], "answer": "will be working"},
            {"question": "The sun ___ (shine) brightly all day tomorrow.",
             "options": ["will be shining", "will shine", "shines"], "answer": "will be shining"},
            {"question": "I ___ (not / sleep) when you call me late.",
             "options": ["won't be sleeping", "won't sleep", "am not sleeping"], "answer": "won't be sleeping"}
        ]
    },
    "past-perfect": {
        "title": "Past Perfect",
        "category": "past",
        "formula": "Had + V3/-ed",
        "examples": ["He had gone"],
        "color": "purple",
        "questions": [
            {"question": "By the time we arrived, the train ___ (leave).", "options": ["had left", "left", "has left"],
             "answer": "had left"},
            {"question": "She ___ (already / finish) her homework before mom asked.",
             "options": ["had already finished", "already finished", "has already finished"],
             "answer": "had already finished"},
            {"question": "They ___ (not / eat) anything before the long journey.",
             "options": ["hadn't eaten", "didn't eat", "haven't eaten"], "answer": "hadn't eaten"},
            {"question": "___ you ever visited London before last year?", "options": ["Had", "Have", "Did"],
             "answer": "Had"},
            {"question": "He realized he ___ (forget) his keys at home.",
             "options": ["had forgotten", "forgot", "has forgotten"], "answer": "had forgotten"},
            {"question": "The garden was dry because it ___ (not / rain) for weeks.",
             "options": ["hadn't rained", "didn't rain", "hasn't rained"], "answer": "hadn't rained"},
            {"question": "She ___ (meet) him once before the party.", "options": ["had met", "met", "has met"],
             "answer": "had met"},
            {"question": "What ___ you done before the police arrived?", "options": ["had", "have", "did"],
             "answer": "had"},
            {"question": "The film ___ (start) when we found our seats.",
             "options": ["had started", "started", "has started"], "answer": "had started"},
            {"question": "I ___ (never / see) such a beautiful sunset before that day.",
             "options": ["had never seen", "never saw", "have never seen"], "answer": "had never seen"},
            {"question": "They ___ (buy) tickets before the box office closed.",
             "options": ["had bought", "bought", "have bought"], "answer": "had bought"},
            {"question": "He ___ (not / read) the book, so he didn't understand the movie.",
             "options": ["hadn't read", "didn't read", "hasn't read"], "answer": "hadn't read"},
            {"question": "___ she locked the door before leaving?", "options": ["Had", "Has", "Did"], "answer": "Had"},
            {"question": "We ___ (clean) the house before guests arrived.",
             "options": ["had cleaned", "cleaned", "have cleaned"], "answer": "had cleaned"},
            {"question": "The snow ___ (stop) by the time we woke up.",
             "options": ["had stopped", "stopped", "has stopped"], "answer": "had stopped"},
            {"question": "I ___ (hear) that song before on the radio.", "options": ["had heard", "heard", "have heard"],
             "answer": "had heard"},
            {"question": "She ___ (not / see) snow until she moved north.",
             "options": ["hadn't seen", "didn't see", "hasn't seen"], "answer": "hadn't seen"},
            {"question": "Why ___ you left the meeting early?", "options": ["had", "have", "did"], "answer": "had"},
            {"question": "He ___ (write) three books before he turned thirty.",
             "options": ["had written", "wrote", "has written"], "answer": "had written"},
            {"question": "They ___ (lose) their map, so they got lost.", "options": ["had lost", "lost", "have lost"],
             "answer": "had lost"},
            {"question": "By 5 PM, he ___ (fix) the broken computer.", "options": ["had fixed", "fixed", "has fixed"],
             "answer": "had fixed"},
            {"question": "She ___ (not / meet) him prior to the conference.",
             "options": ["hadn't met", "didn't meet", "hasn't met"], "answer": "hadn't met"},
            {"question": "___ they finished the report before the deadline?", "options": ["Had", "Have", "Did"],
             "answer": "Had"},
            {"question": "I ___ (lock) all the doors before going to sleep.",
             "options": ["had locked", "locked", "have locked"], "answer": "had locked"},
            {"question": "The fire ___ (destroy) the old building by morning.",
             "options": ["had destroyed", "destroyed", "has destroyed"], "answer": "had destroyed"},
            {"question": "What ___ you said before he interrupted?", "options": ["had", "have", "did"],
             "answer": "had"},
            {"question": "We ___ (book) the tickets before the prices went up.",
             "options": ["had booked", "booked", "have booked"], "answer": "had booked"},
            {"question": "He ___ (never / travel) abroad before that trip.",
             "options": ["had never traveled", "never traveled", "has never traveled"], "answer": "had never traveled"},
            {"question": "She ___ (not / taste) sushi before yesterday.",
             "options": ["hadn't tasted", "didn't taste", "hasn't tasted"], "answer": "hadn't tasted"},
            {"question": "___ you eaten lunch before you came here?", "options": ["Had", "Have", "Did"],
             "answer": "Had"}
        ]
    },
    "present-perfect": {
        "title": "Present Perfect",
        "category": "present",
        "formula": "Have / has + V3/-ed",
        "examples": ["She has visited London"],
        "color": "blue",
        "questions": [
            {"question": "She ___ (visit) Paris three times this year.",
             "options": ["has visited", "visited", "visits"], "answer": "has visited"},
            {"question": "I ___ (just / finish) reading an amazing article.",
             "options": ["have just finished", "just finished", "am just finishing"], "answer": "have just finished"},
            {"question": "They ___ (not / see) this movie yet.",
             "options": ["haven't seen", "didn't see", "haven't saw"], "answer": "haven't seen"},
            {"question": "___ you ever eaten sushi?", "options": ["Have", "Has", "Did"], "answer": "Have"},
            {"question": "He ___ (lose) his wallet, so he can't pay.", "options": ["has lost", "lost", "loses"],
             "answer": "has lost"},
            {"question": "We ___ (live) in this city for over ten years.", "options": ["have lived", "lived", "live"],
             "answer": "have lived"},
            {"question": "She ___ (not / finish) her project so far.",
             "options": ["hasn't finished", "didn't finish", "isn't finishing"], "answer": "hasn't finished"},
            {"question": "What ___ you done to your hair? It looks great!", "options": ["have", "did", "had"],
             "answer": "have"},
            {"question": "The rain ___ (stop), and the sun is shining.", "options": ["has stopped", "stopped", "stops"],
             "answer": "has stopped"},
            {"question": "I ___ (never / be) to South America.",
             "options": ["have never been", "never was", "was never"], "answer": "have never been"},
            {"question": "He ___ (already / buy) tickets for the concert.",
             "options": ["has already bought", "already bought", "bought already"], "answer": "has already bought"},
            {"question": "They ___ (not / call) us this week.",
             "options": ["haven't called", "didn't call", "don't call"], "answer": "haven't called"},
            {"question": "___ your brother found a new job yet?", "options": ["Has", "Have", "Did"], "answer": "Has"},
            {"question": "We ___ (know) each other since childhood.", "options": ["have known", "knew", "know"],
             "answer": "have known"},
            {"question": "Someone ___ (break) the kitchen window.", "options": ["has broken", "broke", "breaks"],
             "answer": "has broken"},
            {"question": "I ___ (read) three books this month.", "options": ["have read", "read", "am reading"],
             "answer": "have read"},
            {"question": "She ___ (not / wake up) yet.",
             "options": ["hasn't woken up", "didn't wake up", "isn't waking up"], "answer": "hasn't woken up"},
            {"question": "Why ___ you closed the window? It's hot.", "options": ["have", "did", "are"],
             "answer": "have"},
            {"question": "The price of oil ___ (rise) again.", "options": ["has risen", "rose", "rises"],
             "answer": "has risen"},
            {"question": "They ___ (build) a brand new playground.", "options": ["have built", "built", "build"],
             "answer": "have built"},
            {"question": "I ___ (already / eat) breakfast.",
             "options": ["have already eaten", "already ate", "eat already"], "answer": "have already eaten"},
            {"question": "She ___ (not / read) this book yet.", "options": ["hasn't read", "didn't read", "hasn't red"],
             "answer": "hasn't read"},
            {"question": "___ you ever met a famous person?", "options": ["Have", "Has", "Did"], "answer": "Have"},
            {"question": "He ___ (write) a very interesting article.", "options": ["has written", "wrote", "writes"],
             "answer": "has written"},
            {"question": "We ___ (not / decide) where to go on holiday.",
             "options": ["haven't decided", "didn't decide", "don't decide"], "answer": "haven't decided"},
            {"question": "What countries ___ you visited in Europe?", "options": ["have", "did", "had"],
             "answer": "have"},
            {"question": "The train ___ (arrive) at the station.", "options": ["has arrived", "arrived", "arrives"],
             "answer": "has arrived"},
            {"question": "She ___ (lose) her keys again.", "options": ["has lost", "lost", "loses"],
             "answer": "has lost"},
            {"question": "They ___ (buy) a new apartment.", "options": ["have bought", "bought", "buy"],
             "answer": "have bought"},
            {"question": "I ___ (forget) your name, sorry.", "options": ["have forgotten", "forgot", "forget"],
             "answer": "have forgotten"}
        ]
    },
    "future-perfect": {
        "title": "Future Perfect",
        "category": "future",
        "formula": "Will + have V3/-ed",
        "examples": ["I will have written"],
        "color": "pink",
        "questions": [
            {"question": "By next year, I ___ (graduate) from university.",
             "options": ["will have graduated", "will graduate", "graduate"], "answer": "will have graduated"},
            {"question": "She ___ (finish) the report by Friday afternoon.",
             "options": ["will have finished", "will finish", "finishes"], "answer": "will have finished"},
            {"question": "They ___ (not / complete) the building by winter.",
             "options": ["won't have completed", "won't complete", "haven't completed"],
             "answer": "won't have completed"},
            {"question": "___ you have finished the task by tomorrow morning?", "options": ["Will", "Do", "Have"],
             "answer": "Will"},
            {"question": "By the time you arrive, we ___ (eat) dinner.",
             "options": ["will have eaten", "will eat", "eat"], "answer": "will have eaten"},
            {"question": "He ___ (write) three books by the end of the year.",
             "options": ["will have written", "will write", "writes"], "answer": "will have written"},
            {"question": "I ___ (save) enough money for a car by next summer.",
             "options": ["will have saved", "will save", "save"], "answer": "will have saved"},
            {"question": "What ___ you have achieved by age thirty?", "options": ["will", "do", "have"],
             "answer": "will"},
            {"question": "The snow ___ (melt) by next week.", "options": ["will have melted", "will melt", "melts"],
             "answer": "will have melted"},
            {"question": "She ___ (not / return) from her trip before Monday.",
             "options": ["won't have returned", "won't return", "hasn't returned"], "answer": "won't have returned"},
            {"question": "___ they have closed the deal by then?", "options": ["Will", "Do", "Have"], "answer": "Will"},
            {"question": "We ___ (live) in this house for ten years next month.",
             "options": ["will have lived", "will live", "live"], "answer": "will have lived"},
            {"question": "The sun ___ (set) by the time we reach home.",
             "options": ["will have set", "will set", "sets"], "answer": "will have set"},
            {"question": "He ___ (not / fix) the car before you need it.",
             "options": ["won't have fixed", "won't fix", "hasn't fixed"], "answer": "won't have fixed"},
            {"question": "___ she have packed her bags by 6 PM?", "options": ["Will", "Has", "Did"], "answer": "Will"},
            {"question": "By midnight, the storm ___ (pass).", "options": ["will have passed", "will pass", "passes"],
             "answer": "will have passed"},
            {"question": "I ___ (read) all these books by the end of the course.",
             "options": ["will have read", "will read", "read"], "answer": "will have read"},
            {"question": "They ___ (repair) the road before winter starts.",
             "options": ["will have repaired", "will repair", "repair"], "answer": "will have repaired"},
            {"question": "Why ___ you have resigned before your contract ends?", "options": ["will", "do", "have"],
             "answer": "will"},
            {"question": "She ___ (achieved) her goal by next month.",
             "options": ["will have achieved", "will achieve", "achieves"], "answer": "will have achieved"},
            {"question": "By tomorrow, I ___ (sign) the contract.",
             "options": ["will have signed", "will sign", "signed"], "answer": "will have signed"},
            {"question": "He ___ (not / finish) the project by Friday.",
             "options": ["won't have finished", "won't finish", "hasn't finished"], "answer": "won't have finished"},
            {"question": "___ you have cleaned the house by the time guests arrive?", "options": ["Will", "Do", "Have"],
             "answer": "Will"},
            {"question": "They ___ (build) the bridge by next autumn.",
             "options": ["will have built", "will build", "built"], "answer": "will have built"},
            {"question": "By next week, prices ___ (increase).",
             "options": ["will have increased", "will increase", "increased"], "answer": "will have increased"},
            {"question": "What ___ you have learned by the end of the course?", "options": ["will", "do", "have"],
             "answer": "will"},
            {"question": "We ___ (reach) our destination before dark.",
             "options": ["will have reached", "will reach", "reached"], "answer": "will have reached"},
            {"question": "She ___ (pay) off her loan by next year.", "options": ["will have paid", "will pay", "paid"],
             "answer": "will have paid"},
            {"question": "The mechanic ___ (repair) your car by 4 PM.",
             "options": ["will have repaired", "will repair", "repaired"], "answer": "will have repaired"},
            {"question": "I ___ (write) the essay by midnight.",
             "options": ["will have written", "will write", "wrote"], "answer": "will have written"}
        ]
    },
    "past-perfect-continuous": {
        "title": "Past Perfect Continuous",
        "category": "past",
        "formula": "Had + been + V-ing",
        "examples": ["I had been writing"],
        "color": "purple",
        "questions": [
            {"question": "He ___ (work) at the company for five years before it closed.",
             "options": ["had been working", "was working", "has been working"], "answer": "had been working"},
            {"question": "It ___ (rain) for hours, so the streets were flooded.",
             "options": ["had been raining", "was raining", "has been raining"], "answer": "had been raining"},
            {"question": "They ___ (not / sleep) well for nights before the exam.",
             "options": ["hadn't been sleeping", "weren't sleeping", "haven't been sleeping"],
             "answer": "hadn't been sleeping"},
            {"question": "___ you waiting long before the bus finally arrived?", "options": ["Had", "Have", "Were"],
             "answer": "Had"},
            {"question": "She was tired because she ___ (clean) the house all morning.",
             "options": ["had been cleaning", "was cleaning", "has been cleaning"], "answer": "had been cleaning"},
            {"question": "What ___ you doing before the accident happened?",
             "options": ["had been", "were", "have been"], "answer": "had been"},
            {"question": "The athletes ___ (train) hard for months before the Olympics.",
             "options": ["had been training", "were training", "have been training"], "answer": "had been training"},
            {"question": "He ___ (study) English for two years before moving to London.",
             "options": ["had been studying", "was studying", "has been studying"], "answer": "had been studying"},
            {"question": "We ___ (drive) for six hours straight and needed a break.",
             "options": ["had been driving", "were driving", "have been driving"], "answer": "had been driving"},
            {"question": "She ___ (not / feel) well for days before seeing a doctor.",
             "options": ["hadn't been feeling", "wasn't feeling", "hasn't been feeling"],
             "answer": "hadn't been feeling"},
            {"question": "___ they playing football before it started to pour?", "options": ["Had", "Were", "Have"],
             "answer": "Had"},
            {"question": "The fire ___ (burn) for hours before firefighters arrived.",
             "options": ["had been burning", "was burning", "has been burning"], "answer": "had been burning"},
            {"question": "I ___ (look) for my keys everywhere before I found them.",
             "options": ["had been looking", "was looking", "have been looking"], "answer": "had been looking"},
            {"question": "They ___ (not / talk) to each other for weeks.",
             "options": ["hadn't been talking", "weren't talking", "haven't been talking"],
             "answer": "hadn't been talking"},
            {"question": "___ she been crying before I opened the door?", "options": ["Had", "Have", "Was"],
             "answer": "Had"},
            {"question": "The machine ___ (make) a strange noise before it broke down.",
             "options": ["had been making", "was making", "has been making"], "answer": "had been making"},
            {"question": "We ___ (wait) in line for over an hour.",
             "options": ["had been waiting", "were waiting", "have been waiting"], "answer": "had been waiting"},
            {"question": "He ___ (try) to fix the engine all afternoon.",
             "options": ["had been trying", "was trying", "has been trying"], "answer": "had been trying"},
            {"question": "Why ___ you been keeping secrets from me?", "options": ["had", "have", "were"],
             "answer": "had"},
            {"question": "She ___ (live) in Paris for a year before she learned French.",
             "options": ["had been living", "was living", "has been living"], "answer": "had been living"},
            {"question": "He ___ (play) guitar for hours before his fingers hurt.",
             "options": ["had been playing", "was playing", "has been playing"], "answer": "had been playing"},
            {"question": "They ___ (not / practice) long before the concert started.",
             "options": ["hadn't been practicing", "weren't practicing", "haven't been practicing"],
             "answer": "hadn't been practicing"},
            {"question": "___ you studying hard before the test was canceled?", "options": ["Had", "Have", "Were"],
             "answer": "Had"},
            {"question": "The wind ___ (blow) fiercely all night.",
             "options": ["had been blowing", "was blowing", "has been blowing"], "answer": "had been blowing"},
            {"question": "She ___ (write) poems for years before publishing one.",
             "options": ["had been writing", "was writing", "has been writing"], "answer": "had been writing"},
            {"question": "What ___ they discussing before I walked in?", "options": ["had been", "were", "have been"],
             "answer": "had been"},
            {"question": "We ___ (search) for a new flat for months.",
             "options": ["had been searching", "were searching", "have been searching"],
             "answer": "had been searching"},
            {"question": "He ___ (not / sleep) well for days prior to the exam.",
             "options": ["hadn't been sleeping", "weren't sleeping", "hasn't been sleeping"],
             "answer": "hadn't been sleeping"},
            {"question": "___ it snowing heavily before we left?", "options": ["Had", "Was", "Have"], "answer": "Had"},
            {"question": "I ___ (run) for an hour when it started to rain.",
             "options": ["had been running", "was running", "have been running"], "answer": "had been running"}
        ]
    },
    "present-perfect-continuous": {
        "title": "Present Perfect Continuous",
        "category": "present",
        "formula": "Have / has + been + V-ing",
        "examples": ["I have been writing"],
        "color": "blue",
        "questions": [
            {"question": "I ___ (learn) English for two years.",
             "options": ["have been learning", "am learning", "had been learning"], "answer": "have been learning"},
            {"question": "She ___ (work) on this project since morning.",
             "options": ["has been working", "is working", "was working"], "answer": "has been working"},
            {"question": "It ___ (rain) all day long.", "options": ["has been raining", "is raining", "rained"],
             "answer": "has been raining"},
            {"question": "They ___ (not / sleep) well recently.",
             "options": ["haven't been sleeping", "aren't sleeping", "didn't sleep"],
             "answer": "haven't been sleeping"},
            {"question": "___ you waiting here for a long time?", "options": ["Have", "Has", "Are"], "answer": "Have"},
            {"question": "He ___ (play) computer games for hours.",
             "options": ["has been playing", "is playing", "played"], "answer": "has been playing"},
            {"question": "We ___ (live) in Kyiv since 2015.", "options": ["have been living", "are living", "lived"],
             "answer": "have been living"},
            {"question": "What ___ you doing for the past two hours?", "options": ["have", "has", "are"],
             "answer": "have"},
            {"question": "The phone ___ (ring) for two minutes, answer it!",
             "options": ["has been ringing", "is ringing", "rang"], "answer": "has been ringing"},
            {"question": "She ___ (not / feel) well lately.",
             "options": ["hasn't been feeling", "isn't feeling", "doesn't feel"], "answer": "hasn't been feeling"},
            {"question": "___ your brother been studying hard for his exams?", "options": ["Has", "Have", "Is"],
             "answer": "Has"},
            {"question": "They ___ (travel) across Europe for a month.",
             "options": ["have been traveling", "are traveling", "traveled"], "answer": "have been traveling"},
            {"question": "I ___ (read) this book all week.", "options": ["have been reading", "am reading", "read"],
             "answer": "have been reading"},
            {"question": "He ___ (not / work) here very long.",
             "options": ["hasn't been working", "isn't working", "didn't work"], "answer": "hasn't been working"},
            {"question": "___ it been snowing outside all morning?", "options": ["Has", "Have", "Is"], "answer": "Has"},
            {"question": "We ___ (prepare) for the party since yesterday.",
             "options": ["have been preparing", "are preparing", "prepared"], "answer": "have been preparing"},
            {"question": "The dog ___ (bark) loudly for ten minutes.",
             "options": ["has been barking", "is barking", "barked"], "answer": "has been barking"},
            {"question": "Why ___ you keeping this from me?", "options": ["have", "has", "are"], "answer": "have"},
            {"question": "She ___ (practice) the piano all afternoon.",
             "options": ["has been practicing", "is practicing", "practiced"], "answer": "has been practicing"},
            {"question": "Prices ___ (rise) continuously over the last year.",
             "options": ["have been rising", "are rising", "rose"], "answer": "have been rising"},
            {"question": "I ___ (wait) for the bus for 30 minutes.",
             "options": ["have been waiting", "am waiting", "waited"], "answer": "have been waiting"},
            {"question": "He ___ (not / feel) well for the past few days.",
             "options": ["hasn't been feeling", "isn't feeling", "didn't feel"], "answer": "hasn't been feeling"},
            {"question": "___ you working here for a long time?", "options": ["Have", "Has", "Are"], "answer": "Have"},
            {"question": "They ___ (build) that road for months.",
             "options": ["have been building", "are building", "built"], "answer": "have been building"},
            {"question": "She ___ (look) for her keys all morning.",
             "options": ["has been looking", "is looking", "looked"], "answer": "has been looking"},
            {"question": "What ___ you doing since we last met?", "options": ["have", "has", "are"], "answer": "have"},
            {"question": "We ___ (discuss) this problem for hours.",
             "options": ["have been discussing", "are discussing", "discussed"], "answer": "have been discussing"},
            {"question": "It ___ (snow) since early morning.", "options": ["has been snowing", "is snowing", "snowed"],
             "answer": "has been snowing"},
            {"question": "He ___ (not / study) hard lately.",
             "options": ["hasn't been studying", "isn't studying", "didn't study"], "answer": "hasn't been studying"},
            {"question": "___ she practicing yoga recently?", "options": ["Has", "Have", "Is"], "answer": "Has"}
        ]
    },
    "future-perfect-continuous": {
        "title": "Future Perfect Continuous",
        "category": "future",
        "formula": "Will + have + been + V-ing",
        "examples": ["I will have been writing"],
        "color": "pink",
        "questions": [
            {"question": "By next year, I ___ (live) here for ten years.",
             "options": ["will have been living", "will live", "have lived"], "answer": "will have been living"},
            {"question": "By December, she ___ (work) at this firm for five years.",
             "options": ["will have been working", "will work", "has worked"], "answer": "will have been working"},
            {"question": "They ___ (not / travel) for long when they reach their destination.",
             "options": ["won't have been traveling", "won't travel", "haven't traveled"],
             "answer": "won't have been traveling"},
            {"question": "___ you have been studying for three hours by 5 PM?", "options": ["Will", "Do", "Have"],
             "answer": "Will"},
            {"question": "By tomorrow morning, it ___ (snow) for two days straight.",
             "options": ["will have been snowing", "will snow", "has snowed"], "answer": "will have been snowing"},
            {"question": "He ___ (run) for an hour by the time the race ends.",
             "options": ["will have been running", "will run", "has run"], "answer": "will have been running"},
            {"question": "We ___ (wait) for over an hour when the train arrives.",
             "options": ["will have been waiting", "will wait", "have waited"], "answer": "will have been waiting"},
            {"question": "What ___ you have been doing for all that time?", "options": ["will", "do", "have"],
             "answer": "will"},
            {"question": "The musicians ___ (play) for four hours straight by midnight.",
             "options": ["will have been playing", "will play", "have played"], "answer": "will have been playing"},
            {"question": "She ___ (not / sleep) for long when her alarm goes off.",
             "options": ["won't have been sleeping", "won't sleep", "hasn't slept"],
             "answer": "won't have been sleeping"},
            {"question": "___ they have been driving for five hours by lunchtime?", "options": ["Will", "Do", "Have"],
             "answer": "Will"},
            {"question": "By next month, I ___ (teach) English for a decade.",
             "options": ["will have been teaching", "will teach", "have taught"], "answer": "will have been teaching"},
            {"question": "The engine ___ (run) for hours before we check it.",
             "options": ["will have been running", "will run", "has run"], "answer": "will have been running"},
            {"question": "He ___ (not / practice) long enough by the tournament.",
             "options": ["won't have been practicing", "won't practice", "hasn't practiced"],
             "answer": "won't have been practicing"},
            {"question": "___ she have been working here for a year by next Monday?", "options": ["Will", "Has", "Did"],
             "answer": "Will"},
            {"question": "By sunset, the ship ___ (sail) across the ocean for a week.",
             "options": ["will have been sailing", "will sail", "has sailed"], "answer": "will have been sailing"},
            {"question": "I ___ (read) this textbook for two weeks by tomorrow.",
             "options": ["will have been reading", "will read", "have read"], "answer": "will have been reading"},
            {"question": "They ___ (build) the bridge for three years by next spring.",
             "options": ["will have been building", "will build", "have built"], "answer": "will have been building"},
            {"question": "Why ___ you have been working for so many hours?", "options": ["will", "do", "have"],
             "answer": "will"},
            {"question": "She ___ (cook) dinner for two hours by the time guests arrive.",
             "options": ["will have been cooking", "will cook", "has cooked"], "answer": "will have been cooking"},
            {"question": "By next July, we ___ (live) in this town for five years.",
             "options": ["will have been living", "will live", "have lived"], "answer": "will have been living"},
            {"question": "He ___ (not / work) there long when he gets promoted.",
             "options": ["won't have been working", "won't work", "hasn't worked"],
             "answer": "won't have been working"},
            {"question": "___ you have been driving for six hours by then?", "options": ["Will", "Do", "Have"],
             "answer": "Will"},
            {"question": "By midnight, it ___ (snow) for 24 hours.",
             "options": ["will have been snowing", "will snow", "has snowed"], "answer": "will have been snowing"},
            {"question": "She ___ (train) for the marathon for six months by May.",
             "options": ["will have been training", "will train", "has trained"], "answer": "will have been training"},
            {"question": "What ___ you have been doing for the last two hours?", "options": ["will", "do", "have"],
             "answer": "will"},
            {"question": "They ___ (play) tennis for two hours by 5 PM.",
             "options": ["will have been playing", "will play", "played"], "answer": "will have been playing"},
            {"question": "By next week, I ___ (study) programming for a year.",
             "options": ["will have been studying", "will study", "studied"], "answer": "will have been studying"},
            {"question": "She ___ (not / sleep) for long when her alarm rings.",
             "options": ["won't have been sleeping", "won't sleep", "hasn't slept"],
             "answer": "won't have been sleeping"},
            {"question": "___ he have been writing his book for a year by next month?",
             "options": ["Will", "Has", "Did"], "answer": "Will"}
        ]
    },
}